넘파이실습

In [1]:
#라이브러리 로딩
import numpy as np

In [2]:
#파이썬 리스트에서 넘파이로 변환
a = [1, 3.14, True, 'hello'] #리스트
b = np.array(a)

In [3]:
#리스트 원소 데이터 타입 확인
print(a)
for element in a:
    print('Data type of {} : {}'.format(element, type(element)))

[1, 3.14, True, 'hello']
Data type of 1 : <class 'int'>
Data type of 3.14 : <class 'float'>
Data type of True : <class 'bool'>
Data type of hello : <class 'str'>


In [4]:
print(b)
for element in b:
    print('Data type of {} : {}'.format(element ,type(element)))

['1' '3.14' 'True' 'hello']
Data type of 1 : <class 'numpy.str_'>
Data type of 3.14 : <class 'numpy.str_'>
Data type of True : <class 'numpy.str_'>
Data type of hello : <class 'numpy.str_'>


In [5]:
#중첩 리스트 생성
a = [[1, 2, 3], [4, 5, 6]]
print(a)

[[1, 2, 3], [4, 5, 6]]


In [6]:
#중첩리스트 데이터 타입 확인
type(a)

list

In [7]:
#중첩 리스트를 넘파이 배열로 변환 ==> 2차원인 행렬로 변환
b = np.array(a)
print(b)

[[1 2 3]
 [4 5 6]]


In [8]:
#행렬 데이터 타입 확인
type(b)

numpy.ndarray

In [9]:
# 배열(array)의 shape 확인
b.shape #(2,3)

(2, 3)

In [10]:
# 배열(array)의 차원 확인
b.ndim #2

2

In [11]:
# 배열(array)내 총 원소 개수 확인
b.size

6

In [12]:
# 2x3 행렬을 3x2로 바꿔보자.
print(b.reshape(3, 2)) #단순하게 reshape 메소드를 호출하면 된다.

[[1 2]
 [3 4]
 [5 6]]


In [13]:
# 배열 요소 데이터타입 변경: 정수 -> 실수
b= np.array(a, dtype=np.float64)
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [14]:
# 배열 요소 데이터타입 변경: 실수 -> 정수
b = b.astype(np.int64)
print(b)

[[1 2 3]
 [4 5 6]]


넘파이 배열 인덱싱

In [15]:
#새로운 배열 arr 생성
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [16]:
# 배열 원소 가져오기
print(arr[0]) # 첫번째
print(arr[3]) # 네번째
print(arr[-1]) # 배열마지막 원소

1
4
5


2차원 배열 인덱싱

In [17]:
#2차원 배열 생성
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

In [18]:
#1행 1열 가져오기
arr_2d[0,0]

1

In [19]:
#2행 3열 가져오기
arr_2d[1,2]

6

배열 슬라이싱

In [20]:
# 슬라이싱 실습에 사용할 넘파이 배열을 arange라는 넘파이의 메서드르 이용하여 만들어보자

arr_2d = np.arange(1,7).reshape(2,3)

print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [21]:
# 첫번째 행 전체 가져오기

print(arr_2d[0, :]) # 첫번째 행에 대해서 모든 열의 값 출력

[1 2 3]


In [22]:
#세번째 열 전체 출력

print(arr_2d[:,2]) # 3번째 열에 있는 모든 원소 출력

[3 6]


In [23]:
#전체 행 두번째 열까지 모두 출력

print(arr_2d[:, :2])

[[1 2]
 [4 5]]


판다스 pandas 소개

In [24]:
#라이브러리 로딩
import pandas as pd

데이터 생성

In [25]:
# 실습에 사용할 샘플 딕셔너리 생성

data ={
    "이름": ["아이유", "김연아", "홍길동", "장범준", "강감찬"],
    "학과": ["국문학", "수학", "컴퓨터", "철학", "경영학"],
    "성적": [3.0, 1.0, 3.5, 2.7, 4.0]
}


In [26]:
data

{'이름': ['아이유', '김연아', '홍길동', '장범준', '강감찬'],
 '학과': ['국문학', '수학', '컴퓨터', '철학', '경영학'],
 '성적': [3.0, 1.0, 3.5, 2.7, 4.0]}

In [31]:
# 딕셔너리 타입인 data를 pd.DataFrame() 인자로 넣어주면 됩니다.
df = pd.DataFrame(data)

display(df)

이름   학과   성적
0  아이유  국문학  3.0
1  김연아   수학  1.0
2  홍길동  컴퓨터  3.5
3  장범준   철학  2.7
4  강감찬  경영학  4.0

데이터 csv로 저장하기

In [33]:
#데이터프레임을 csv로 저장 --> to_csv 메소드 이용
df.to_csv('./stuedent.csv', sep=',', index=False)

In [35]:
df = pd.read_csv('./stuedent.csv')
display(df)

이름   학과   성적
0  아이유  국문학  3.0
1  김연아   수학  1.0
2  홍길동  컴퓨터  3.5
3  장범준   철학  2.7
4  강감찬  경영학  4.0

pandas 원하는 데이터 선택하기

1)슬라이싱(slicing)

In [36]:
#데이터 슬라이싱
df[1:5] #데이터의 1번행 부터 4번행까지

이름   학과   성적
1  김연아   수학  1.0
2  홍길동  컴퓨터  3.5
3  장범준   철학  2.7
4  강감찬  경영학  4.0

In [38]:
df[0:3] # 첫번째부터 세번째 까지

이름   학과   성적
0  아이유  국문학  3.0
1  김연아   수학  1.0
2  홍길동  컴퓨터  3.5

In [39]:
df[0:] #모든 행 데이터에 접근

이름   학과   성적
0  아이유  국문학  3.0
1  김연아   수학  1.0
2  홍길동  컴퓨터  3.5
3  장범준   철학  2.7
4  강감찬  경영학  4.0

In [40]:
df[:]

이름   학과   성적
0  아이유  국문학  3.0
1  김연아   수학  1.0
2  홍길동  컴퓨터  3.5
3  장범준   철학  2.7
4  강감찬  경영학  4.0

2)인덱싱

In [41]:
df[1] #key error

KeyError: 1

In [42]:
df['이름']

0    아이유
1    김연아
2    홍길동
3    장범준
4    강감찬
Name: 이름, dtype: object

In [43]:
df['학과']

0    국문학
1     수학
2    컴퓨터
3     철학
4    경영학
Name: 학과, dtype: object

fancy indexing

In [44]:
#인덱싱시 리스트로 값을 주면 됨
df[['이름','학과']]

이름   학과
0  아이유  국문학
1  김연아   수학
2  홍길동  컴퓨터
3  장범준   철학
4  강감찬  경영학

In [45]:
fancy_list = ['이름', '학과']

df[fancy_list]

이름   학과
0  아이유  국문학
1  김연아   수학
2  홍길동  컴퓨터
3  장범준   철학
4  강감찬  경영학

In [46]:
#컬럼 입력시 순서는 중요하지 않습니다.
df[['학과', '이름']]

학과   이름
0  국문학  아이유
1   수학  김연아
2  컴퓨터  홍길동
3   철학  장범준
4  경영학  강감찬

슬라이싱 + 인덱싱

In [47]:
df[1:3][['학과', '이름']]

학과   이름
1   수학  김연아
2  컴퓨터  홍길동

In [48]:
df[['학과', '이름']][1:3]

학과   이름
1   수학  김연아
2  컴퓨터  홍길동

Boolean indexing

(연산자를 이용하여 인덱싱 수행 e.g. ==, !=, >, etc)

In [49]:
# 수학과 소속인 한색의 데이터만

df[df['학과'] == '수학']

이름  학과   성적
1  김연아  수학  1.0

In [50]:
#성적

df[df['성적'] >= 2]

이름   학과   성적
0  아이유  국문학  3.0
2  홍길동  컴퓨터  3.5
3  장범준   철학  2.7
4  강감찬  경영학  4.0

Pandas 고급인덱싱 loc&iloc 인덱서

In [51]:
#한개의 행에 대해서만 loc indexing
df.loc[3]

이름    장범준
학과     철학
성적    2.7
Name: 3, dtype: object

In [52]:
#행에 대해서 fancy indexing
df.loc[[1, 3, 4]]

이름   학과   성적
1  김연아   수학  1.0
3  장범준   철학  2.7
4  강감찬  경영학  4.0

In [53]:
df.loc[[1, 3, 4],:]

이름   학과   성적
1  김연아   수학  1.0
3  장범준   철학  2.7
4  강감찬  경영학  4.0

In [55]:
df.loc[[1, 3, 4],'이름':'성적']

이름   학과   성적
1  김연아   수학  1.0
3  장범준   철학  2.7
4  강감찬  경영학  4.0

In [57]:
df.loc[[1, 3, 4],['이름', '성적']]

이름   성적
1  김연아  1.0
3  장범준  2.7
4  강감찬  4.0

In [58]:
# 아래와 같이 iloc 인덱서를 사용할 수 있습니다.
df.iloc[[1, 3, 4], 0:2]

이름   학과
1  김연아   수학
3  장범준   철학
4  강감찬  경영학

In [60]:
# loc + boolean indexing

df.loc[df['성적'] % 2 != 0, ['이름', '학과']]

이름   학과
0  아이유  국문학
1  김연아   수학
2  홍길동  컴퓨터
3  장범준   철학